export const mentalAbilityQuestions = [
  {
    type: "mental_ability",
    category: "logical_reasoning",
    difficulty: "easy",
    question: "If all Bloops are Razzies and all Razzies are Lazzies, then all Bloops are definitely Lazzies?",
    options: ["True", "False", "Cannot be determined", "None of the above"],
    correctAnswer: "True",
  },
  {
    type: "mental_ability",
    category: "pattern_recognition",
    difficulty: "medium",
    question: "What comes next in the series: 2, 6, 12, 20, 30, ?",
    options: ["40", "42", "44", "46"],
    correctAnswer: "42",
  },
  {
    type: "mental_ability",
    category: "quantitative",
    difficulty: "easy",
    question: "If a train travels 60 km in 45 minutes, what is its speed in km/h?",
    options: ["60", "70", "80", "90"],
    correctAnswer: "80",
  },
  {
    type: "mental_ability",
    category: "aptitude",
    difficulty: "medium",
    question: "A is twice as old as B. Five years ago, A was three times as old as B. What is B's current age?",
    options: ["10", "15", "20", "25"],
    correctAnswer: "10",
  },
  {
    type: "mental_ability",
    category: "logical_reasoning",
    difficulty: "medium",
    question: "In a certain code, COMPUTER is written as RFUVQNPC. How is MEDICINE written in that code?",
    options: ["EOJDEJFM", "MFEJDJOE", "NFEJEOJD", "EOJDJEFM"],
    correctAnswer: "EOJDJEFM",
  },
  {
    type: "mental_ability",
    category: "pattern_recognition",
    difficulty: "hard",
    question: "Find the odd one out: 3, 5, 11, 14, 17, 21",
    options: ["3", "5", "14", "21"],
    correctAnswer: "14",
  },
  {
    type: "mental_ability",
    category: "quantitative",
    difficulty: "medium",
    question: "What is 15% of 200?",
    options: ["20", "25", "30", "35"],
    correctAnswer: "30",
  },
  {
    type: "mental_ability",
    category: "aptitude",
    difficulty: "hard",
    question: "A can complete a work in 12 days and B can complete it in 18 days. If they work together, in how many days will they complete the work?",
    options: ["6.5 days", "7.2 days", "8 days", "9 days"],
    correctAnswer: "7.2 days",
  },
  {
    type: "mental_ability",
    category: "logical_reasoning",
    difficulty: "easy",
    question: "Which word does NOT belong with the others?",
    options: ["Rose", "Tulip", "Daisy", "Tree"],
    correctAnswer: "Tree",
  },
  {
    type: "mental_ability",
    category: "pattern_recognition",
    difficulty: "easy",
    question: "Complete the sequence: A, C, E, G, ?",
    options: ["H", "I", "J", "K"],
    correctAnswer: "I",
  },
  {
    type: "mental_ability",
    category: "quantitative",
    difficulty: "hard",
    question: "If the cost price of 12 pens is equal to the selling price of 10 pens, what is the profit percentage?",
    options: ["10%", "15%", "20%", "25%"],
    correctAnswer: "20%",
  },
  {
    type: "mental_ability",
    category: "aptitude",
    difficulty: "easy",
    question: "What is the next number in the sequence: 1, 4, 9, 16, 25, ?",
    options: ["30", "32", "36", "40"],
    correctAnswer: "36",
  },
  {
    type: "mental_ability",
    category: "logical_reasoning",
    difficulty: "hard",
    question: "If FRIEND is coded as HUMJTK, how is CANDLE coded?",
    options: ["EDRIRL", "DEQHQK", "ECSNJF", "DCQMJG"],
    correctAnswer: "ECSNJF",
  },
  {
    type: "mental_ability",
    category: "pattern_recognition",
    difficulty: "medium",
    question: "What is the missing number: 8, 27, 64, ?, 216",
    options: ["100", "125", "144", "169"],
    correctAnswer: "125",
  },
  {
    type: "mental_ability",
    category: "quantitative",
    difficulty: "medium",
    question: "A shopkeeper marks his goods 40% above cost price but allows a discount of 20%. What is his profit percentage?",
    options: ["10%", "12%", "15%", "18%"],
    correctAnswer: "12%",
  },
];
